import { UCPCRowData } from "./UCPCRow";

const UCPCData: UCPCRowData[] = [
  {
    year: "2023",
    phase: "FINALS",
    contest: "2023 여름 대회 본선",
    contestLink: "https://2023.ucpc.me/",
    team: "작혼우인전3of4너만오면고",
    score: 3,
    penalty: 641,
    rank: 41,
    totalTeams: 44,
  },
  {
    year: "2023",
    phase: "PRELIMINARY",
    contest: "2023 여름 대회 예선",
    contestLink: "https://2023.ucpc.me/",
    team: "작혼우인전3of4너만오면고",
    score: 7,
    penalty: 540,
    rank: 44,
    totalTeams: 222,
  },
  {
    year: "2021",
    phase: "FINALS",
    contest: "2021 여름 대회 본선",
    contestLink: "https://2021.ucpc.me/",
    team: "Redshift (박수현, 이준석, 전해성)",
    score: 6,
    penalty: 662,
    rank: 12,
    totalTeams: 60,
    award: "5등상",
  },
  {
    year: "2021",
    phase: "PRELIMINARY",
    contest: "2021 여름 대회 예선",
    contestLink: "https://2021.ucpc.me/",
    team: "Redshift (박수현, 이준석, 전해성)",
    score: 8,
    penalty: 518,
    rank: 18,
    totalTeams: 267,
  },
  {
    year: "2019",
    phase: "PRELIMINARY",
    contest: "2019 여름 대회 예선",
    contestLink: "https://2019.ucpc.me/",
    team: "🐟 (박수현, 이준석, 박건)",
    score: 3,
    penalty: 78,
    rank: 72,
    totalTeams: 270,
    firstToSolve: ["B"],
  },
];

export default UCPCData;
