import { ProblemsettingRowData } from "./ProblemsettingRow";

const ProblemsettingData: ProblemsettingRowData[] = [
  {
    year: "2022",
    contest: "2022 Sogang Programming Contest (SPC)",
    contestLink: "https://icpc.team/spc",
    title: "유통기한",
    number: "Master B",
    bojProblemId: 26083,
  },
  {
    year: "2022",
    contest: "2022 Sogang Programming Contest (SPC)",
    contestLink: "https://icpc.team/spc",
    title: "슈퍼 블랙잭",
    number: "Champion H",
    bojProblemId: 26096,
  },
  {
    year: "2022",
    contest: "전국연합 여름 대회 (UCPC) 2022 예선",
    contestLink: "https://2022.ucpc.me",
    title: "solved.ac 2022",
    number: "E",
    bojProblemId: 25318,
  },
  {
    year: "2021",
    contest: "2021 Sogang Programming Contest (SPC)",
    contestLink: "https://icpc.team/spc",
    title: "Ресторан",
    number: "Master A",
    bojProblemId: 23738,
  },
  {
    year: "2021",
    contest: "2021 Sogang Programming Contest (SPC)",
    contestLink: "https://icpc.team/spc",
    title: "와드",
    number: "Champion B",
    bojProblemId: 23747,
  },
  {
    year: "2021",
    contest: "2021 Sogang Programming Contest (SPC)",
    contestLink: "https://icpc.team/spc",
    title: "연결 요소와 쿼리",
    number: "Champion H",
    bojProblemId: 23753,
    coAuthored: "문제 원형 개발",
  },
  {
    year: "2021",
    contest: "2021 신촌연합 여름 대회 (SUAPC)",
    contestLink: "https://icpc-sinchon.io/suapc",
    title: "조각 체스판",
    number: "C",
    bojProblemId: 22983,
  },
  {
    year: "2021",
    contest: "2021 신촌연합 여름 대회 (SUAPC)",
    contestLink: "https://icpc-sinchon.io/suapc",
    title: "다꾸",
    number: "L",
    bojProblemId: 22992,
  },
  {
    year: "2021",
    contest: "2021 신촌연합 겨울 대회 (SUAPC)",
    contestLink: "https://icpc-sinchon.io/suapc",
    title: "반짝반짝",
    number: "C",
    bojProblemId: 20938,
  },
  {
    year: "2021",
    contest: "2021 신촌연합 여름 대회 (SUAPC)",
    contestLink: "https://icpc-sinchon.io/suapc",
    title: "성싶당",
    number: "F",
    bojProblemId: 20941,
    coAuthored: "지문 작성 및 데이터 준비",
  },
  {
    year: "2020",
    contest: "2020 신촌연합 여름 대회 (SUAPC)",
    contestLink: "https://icpc-sinchon.io/suapc",
    title: "꿀벌",
    number: "1B",
    bojProblemId: 19573,
  },
  {
    year: "2020",
    contest: "2020 신촌연합 여름 대회 (SUAPC)",
    contestLink: "https://icpc-sinchon.io/suapc",
    title: "난개발",
    number: "2H",
    bojProblemId: 19584,
  },
  {
    year: "2020",
    contest: "2020 신촌연합 여름 대회 (SUAPC)",
    contestLink: "https://icpc-sinchon.io/suapc",
    title: "전설",
    number: "1H",
    bojProblemId: 19585,
  },
  {
    year: "2020",
    contest: "전국연합 여름 대회 (UCPC) 2020 예선",
    contestLink: "https://2020.ucpc.me",
    title: "수학은 비대면강의입니다",
    number: "A",
    bojProblemId: 19532,
  },
  {
    year: "2019",
    contest: "2019 Sogang Programming Contest (SPC)",
    contestLink: "https://icpc.team/spc",
    title: "1998년생인 내가 태국에서는 2541년생?!",
    number: "Master A",
    bojProblemId: 18108,
  },
  {
    year: "2019",
    contest: "2019 Sogang Programming Contest (SPC)",
    contestLink: "https://icpc.team/spc",
    title: "solved.ac",
    number: "Champion A",
    bojProblemId: 18110,
  },
  {
    year: "2019",
    contest: "2019 Sogang Programming Contest (SPC)",
    contestLink: "https://icpc.team/spc",
    title: "7-세그먼트 디스플레이",
    number: "Master F",
    bojProblemId: 18118,
  },
  {
    year: "2019",
    contest: "2019 Sogang Programming Contest (SPC)",
    contestLink: "https://icpc.team/spc",
    title: "평행우주",
    number: "Champion H",
    bojProblemId: 18123,
  },
];

export default ProblemsettingData;
