name: Build and Deploy Site
on:
  push:
    branches:
      - main
      - feature/2023
      - "releases/**"
jobs:
  build-dev:
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
  build-stable:
    # if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PUBLIC_URL: https://shiftpsh.com
      GENERATE_SOURCEMAP: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: out
          bucket: ${{ vars.S3_BUCKET_PRODUCTION }}
          bucket-region: ${{ vars.S3_BUCKET_REGION }}
          dist-id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID_PRODUCTION }}
          no-cache: true
          private: true
