name: Daily Build and Deploy
on:
  schedule:
    - cron: "0 0 * * *" # Every day
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PUBLIC_URL: https://shiftpsh.com
      GENERATE_SOURCEMAP: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: out
          bucket: ${{ vars.S3_BUCKET_PRODUCTION }}
          bucket-region: ${{ vars.S3_BUCKET_REGION }}
          dist-id: ${{ vars.CLOUDFRONT_DISTRIBUTION_ID_PRODUCTION }}
          no-cache: true
          private: true
