import { ICPCRowData } from "./ICPCRow";

const ICPCData: ICPCRowData[] = [
  {
    year: "2023-2024",
    phase: "SUPERREGIONAL",
    venue: "하노이",
    contest: "2024 아시아태평양지역 챔피언십",
    contestLink: "https://icpc.asia/",
    team: "Redshift (박수현, 이준석, 채성우)",
    score: 5,
    penalty: 631,
    rank: 37,
    totalTeams: 65,
  },
  {
    year: "2023-2024",
    phase: "REGIONAL",
    venue: "자카르타",
    contest: "2023 아시아 자카르타 리저널",
    contestLink: "https://competition.binus.ac.id/icpc2023/",
    team: "Redshift (박수현, 이준석, 채성우)",
    score: 6,
    penalty: 394,
    rank: 15,
    totalTeams: 80,
  },
  {
    year: "2023-2024",
    phase: "REGIONAL",
    venue: "서울",
    contest: "2023 아시아 서울 리저널",
    contestLink: "https://icpckorea.org/2023-seoul/regional",
    team: "Redshift (박수현, 이준석, 채성우)",
    score: 6,
    penalty: 576,
    rank: 19,
    totalTeams: 74,
    firstToSolve: ["B"],
  },
  {
    year: "2023-2024",
    phase: "NATIONAL",
    venue: "서울",
    contest: "2023 대학생 프로그래밍 경시대회 온라인 예선",
    contestLink: "https://icpckorea.org/2023-seoul/preliminary",
    team: "Redshift (박수현, 이준석, 채성우)",
    score: 6,
    penalty: 537,
    rank: 17,
    totalTeams: 351,
  },
  {
    year: "2019-2020",
    phase: "FINALS",
    venue: "모스크바",
    contest: "제44회 ICPC 월드 파이널",
    contestLink: "https://worldfinals.icpc.global/",
    team: "Redshift (박수현, 이준석, 이상원)",
    score: 3,
    penalty: 649,
    rank: 87,
    totalTeams: 117,
  },
  {
    year: "2019-2020",
    phase: "REGIONAL",
    venue: "방콕",
    contest: "2019 아시아 방콕 리저널",
    contestLink: "https://acm-icpc.eng.chula.ac.th/",
    team: "Redshift (박수현, 이준석, 박건)",
    score: 3,
    penalty: 359,
    rank: 31,
    totalTeams: 60,
  },
  {
    year: "2019-2020",
    phase: "REGIONAL",
    venue: "서울",
    contest: "2019 아시아 서울 리저널",
    contestLink: "https://icpckorea.org/2019-seoul/regional",
    team: "Redshift (박수현, 이준석, 박건)",
    score: 7,
    penalty: 718,
    rank: 15,
    totalTeams: 92,
    firstToSolve: ["C", "J"],
    award: "장려상",
  },
  {
    year: "2019-2020",
    phase: "NATIONAL",
    venue: "서울",
    contest: "2019 대학생 프로그래밍 경시대회 온라인 예선",
    contestLink: "https://icpckorea.org/2019-seoul/2019-preliminary",
    team: "Redshift (박수현, 이준석, 박건)",
    score: 6,
    penalty: 263,
    rank: 17,
    totalTeams: 695,
  },
  {
    year: "2018-2019",
    phase: "NATIONAL",
    venue: "서울",
    contest: "2018 대학생 프로그래밍 경시대회 온라인 예선",
    contestLink: "https://icpckorea.org/2018-seoul/preliminary",
    team: "algorinewbie (박수현, 이태한, 이경희)",
    score: 3,
    penalty: 242,
    rank: 257,
    totalTeams: 623,
  },
];

export default ICPCData;
